spring:
  redis:
    redisson:
      nodesConfig:
        - edgeId: EDGE_SITE_1
          configProperties: |
            sentinelServersConfig:
              idleConnectionTimeout: 10000
              connectTimeout: 10000
              timeout: 3000
              retryAttempts: 3
              retryInterval: 1500
              failedSlaveReconnectionInterval: 3000
              failedSlaveCheckInterval: 60000
              password: password123
              clientName: settings-sync-1
              subscriptionsPerConnection: 1
              subscriptionConnectionMinimumIdleSize: 1
              subscriptionConnectionPoolSize: 50
              slaveConnectionMinimumIdleSize: 24
              slaveConnectionPoolSize: 64
              masterConnectionMinimumIdleSize: 24
              masterConnectionPoolSize: 24
              readMode: SLAVE
              subscriptionMode: SLAVE
              sentinelAddresses:
              - redis://sentinel01:26379
              - redis://sentinel02:26379
              - redis://sentinel03:26379
              masterName: mymaster
              database: 0
            threads: 1
            nettyThreads: 2
            transportMode: NIO
